### ISSUE TITLE
如何使用，未生效？

### ISSUE THREAD

**Issue by Liujunhua007** [extremeblackliu/NCMAutoDumper#1]
![image](https://github.com/extremeblackliu/NCMAutoDumper/assets/62129047/37bb11e9-1f25-4ce6-9509-69fc60e3fac2)
放到这个地方，试着下载了一首歌，没有转换，是否与C++17有关，这是什么软件去哪下载呢？
![image](https://github.com/extremeblackliu/NCMAutoDumper/assets/62129047/63fd01b7-847d-4541-bed1-5a19a0cb1131)
![image](https://github.com/extremeblackliu/NCMAutoDumper/assets/62129047/4ba25d8d-84b5-48e1-a3e9-000a6546ce0f)

**Comment by eeacks** [comment]
网易云版本是多少？
您为什么要提及c++17，是自己修改然后编译过了吗？

**Comment by Liujunhua007** [comment]
> 网易云版本是多少？ 您为什么要提及c++17，是自己修改然后编译过了吗？
我的是这个版本，下载的是最新的release那个，说支持3.0的
![image](https://github.com/extremeblackliu/NCMAutoDumper/assets/62129047/57e19e0f-afad-4455-9157-b16c371b164b)
我看到readme说，但是我的VC 2017运行库应该是有的，我运行游戏没有问题。
要求
至少 C++ 17
Windows

**Comment by eeacks** [comment]
明白了，是我写的有误导性了，修改了一下readme。
你可以点击右上角的设置按钮，然后找到关于网易云音乐，可以看到具体的版本号

**Comment by Liujunhua007** [comment]
> 明白了，是我写的有误导性了，修改了一下readme。 你可以点击右上角的设置按钮，然后找到关于网易云音乐，可以看到具体的版本号

![image](https://github.com/extremeblackliu/NCMAutoDumper/assets/62129047/68e7a890-510b-47dc-9eee-065441214104)
大佬这个呀，上面回复已经发了

**Comment by eeacks** [comment]
owo不好意思，你的回复文本变成一团了我还以为引用了之前的图片，灯下黑了。
但是你的网易云版本是2.10.13？如果是2.0版本的网易云，你应该使用更早一些的版本，下载这个试试，复制到目录之后重启一下网易云
https://github.com/extremeblackliu/NCMAutoDumper/releases/tag/public

**Comment by Liujunhua007** [comment]
> owo不好意思，你的回复文本变成一团了我还以为引用了之前的图片，灯下黑了。 但是你的网易云版本是2.10.13？如果是2.0版本的网易云，你应该使用更早一些的版本，下载这个试试，复制到目录之后重启一下网易云 https://github.com/extremeblackliu/NCMAutoDumper/releases/tag/public

原来如此，可以使用了，就是后缀名变成这样
![image](https://github.com/extremeblackliu/NCMAutoDumper/assets/62129047/7321959a-14cc-41dc-933b-1b7bf6519cb2)
~~~~

**Comment by eeacks** [comment]
后缀名一般只认最后一个点号的，所以在结尾是`.mp3`的时候`.ncm`将会被当做文件名的一部分，现在已经是普通的MP3文件了
